name: Run Tests
run-name: ${{ gitea.actor }} has published changes
on: [push]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@v4
      - name: Install Emacs
        run: apt-get update && apt-get install -y git emacs-nox
      - uses: actions/cache@v4
        id: cache-cask-packages
        with:
          path: .cask
          key: cache-cask-packages-000
      - uses: actions/cache@v4
        id: cache-cask-executable
        with:
          path: ~/.cask
          key: cache-cask-executable-000
      - uses: cask/setup-cask@master
        if: steps.cache-cask-executable.outputs.cache-hit != 'true'
        with:
          version: snapshot
      - run: echo "$HOME/.cask/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          cask install
      - name: Run Tests
        uses: leotaku/elisp-check@master
        with:
          check: ert
          file: "test/*-test.el"
