name: Run Tests
run-name: ${{ github.actor }} has published changes
on: [push]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@v4
      - name: Install Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: 30.2
      - name: Install dependencies
        run: |
          cask install
      - name: Run Tests
        uses: leotaku/elisp-check@master
        with:
          check: ert
          file: "test/*-test.el"
