name: Run Tests
run-name: ${{ github.actor }} has published changes
on: [push]

jobs:
  run-tests:
    name: Run Tests
    runs-on: linux
    steps:
      - name: Check Out Source
        uses: actions/checkout@v4
      - name: Install Emacs
        uses: jcs090218/setup-emacs@master
      - name: Run Tests
        uses: leotaku/elisp-check@master
        with:
          check: ert
          file: "test/*-test.el"
